# Generated by Django 5.2.7 on 2025-11-04 08:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireLot',
            fields=[
                ('lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_manufactured', models.IntegerField(verbose_name='ปีที่ผลิต')),
                ('date_in', models.DateField(verbose_name='วันที่รับเข้า')),
                ('quantity_in', models.IntegerField(default=0, verbose_name='จำนวนรับเข้า')),
            ],
            options={
                'verbose_name': 'ล็อตยาง (Stock In)',
                'verbose_name_plural': 'ล็อตยาง (Stock In)',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'แอดมิน'), ('staff', 'พนักงาน')], default='staff', max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StockOutTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_out', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่เบิกออก')),
                ('quantity_out', models.IntegerField(default=0, verbose_name='จำนวนที่เบิก')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out_transactions', to=settings.AUTH_USER_MODEL, verbose_name='พนักงาน')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='stocks_app.tirelot', verbose_name='ล็อตที่เบิก')),
            ],
            options={
                'verbose_name': 'ประวัติการเบิกออก',
                'verbose_name_plural': 'ประวัติการเบิกออก (Stock Out)',
                'ordering': ['-date_out'],
            },
        ),
        migrations.CreateModel(
            name='TireProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50, verbose_name='ยี่ห้อ')),
                ('pattern', models.CharField(max_length=50, verbose_name='ลายดอกยาง')),
                ('size', models.CharField(max_length=50, verbose_name='ขนาด')),
            ],
            options={
                'verbose_name': 'ข้อมูลยาง (Master)',
                'verbose_name_plural': 'ข้อมูลยาง (Master)',
                'unique_together': {('brand', 'pattern', 'size')},
            },
        ),
        migrations.AddField(
            model_name='tirelot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='stocks_app.tireproduct', verbose_name='สินค้า'),
        ),
    ]
