# Generated by Django 5.2.8 on 2025-11-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tireproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
    ]
