# Generated by Django 5.2.8 on 2025-11-16 09:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0003_tirelot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tirelot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='ราคา'),
        ),
    ]
