
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y gcc libpq-dev && apt-get clean

# Install Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend source code
COPY . .

# Run with Gunicorn in production mode
CMD sh -c "python manage.py collectstatic --noinput && gunicorn stock_api.wsgi:application --bind 0.0.0.0:8000"
